### PR TITLE
allow php8 in composer.json

### PR DESCRIPTION
**Pull request by sergiy-petrov**

### CODE REVIEW

**Comment by sergiy-petrov** [comment]
is there any chance to run Travis build?

**Comment by sergiy-petrov** [comment]
@has-well could you tag new version of the package and try to run travis tests?

**Comment by has-well** [comment]
Hello, travis-ci starting build from master branch, but it is not connected to this repository, you can fork repository and start testing by yourself with travis, or locally.

**Comment by has-well** [comment]
https://travis-ci.org/github/has-well/php-sdk-v2 This is example, in release 1.0.7 i fix issue for unittest

**Pull request merged**
